#!/usr/bin/env python3
"""Build the Edwin allowlist from the PwC Active staff list XLSX.

Usage:
  python3 backend/scripts/build-allowlist.py \
    --input '/Users/bkaaki001/Downloads/Active staff list.xlsx' \
    --output backend/config/allowlist.txt

The script never echoes names, workday ids, or emails to stdout. It prints
only aggregate statistics so the output can be pasted into tickets safely.

Output file format: one lowercased email per line, sorted, with a short
comment header (generation timestamp + row count). The file is intended to
be gitignored and shipped with the Azure deployment bundle only.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import openpyxl

EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# Manual extras -- emails approved for access but not present in the HR xlsx
# (e.g., onboarding lag, contractors, cross-LoS guests). Kept here instead of
# mutating the generated allowlist so regenerating from a fresh xlsx never
# silently drops these people. Review and prune this list whenever the HR
# xlsx is refreshed.
MANUAL_EXTRAS: frozenset[str] = frozenset({
    "amr.shalaby@pwc.com",
    "gautam.c.sharma@pwc.com",
    "mounir.d.doumani@pwc.com",
    "musab.a.banaamah@pwc.com",
    "tarek.sultanem@pwc.com",
})


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build Edwin allowlist from XLSX")
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Path to 'Active staff list.xlsx'",
    )
    parser.add_argument(
        "--output",
        default=Path("backend/config/allowlist.txt"),
        type=Path,
        help="Where to write the allowlist (defaults to backend/config/allowlist.txt)",
    )
    parser.add_argument(
        "--include-statuses",
        default=None,
        help="Optional comma-separated list of Status values to include (case-insensitive). Omit to include all rows.",
    )
    parser.add_argument(
        "--email-column",
        default="PwC email",
        help="Name of the column that holds the work email (default: 'PwC email')",
    )
    parser.add_argument(
        "--status-column",
        default="Status",
        help="Name of the column that holds the employment status (default: 'Status')",
    )
    return parser.parse_args()


def find_column(header: tuple, name: str) -> int:
    target = name.strip().lower()
    for i, value in enumerate(header):
        if value is not None and str(value).strip().lower() == target:
            return i
    raise SystemExit(f"Column not found in header: {name!r}")


def main() -> int:
    args = parse_args()

    if not args.input.is_file():
        raise SystemExit(f"Input file not found: {args.input}")

    wb = openpyxl.load_workbook(args.input, read_only=True, data_only=True)
    sheet_name = wb.sheetnames[0]
    ws = wb[sheet_name]
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        raise SystemExit("Input sheet is empty")

    header = rows[0]
    data_rows = rows[1:]

    email_col = find_column(header, args.email_column)
    status_col = find_column(header, args.status_column)

    wanted_statuses: set[str] | None = None
    if args.include_statuses:
        wanted_statuses = {s.strip().lower() for s in args.include_statuses.split(",") if s.strip()}

    total_rows = len(data_rows)
    seen_emails: set[str] = set()
    status_counter: Counter[str] = Counter()
    skipped_no_email = 0
    skipped_bad_email = 0
    skipped_status = 0

    for row in data_rows:
        if email_col >= len(row):
            skipped_no_email += 1
            continue
        raw_email = row[email_col]
        if not raw_email:
            skipped_no_email += 1
            continue

        status_val = row[status_col] if status_col < len(row) and row[status_col] is not None else ""
        status_str = str(status_val).strip()
        status_counter[status_str or "(blank)"] += 1

        if wanted_statuses is not None and status_str.lower() not in wanted_statuses:
            skipped_status += 1
            continue

        email = str(raw_email).strip().lower()
        if not EMAIL_RE.match(email):
            skipped_bad_email += 1
            continue

        seen_emails.add(email)

    manual_new = sorted(MANUAL_EXTRAS - seen_emails)
    seen_emails |= MANUAL_EXTRAS

    args.output.parent.mkdir(parents=True, exist_ok=True)

    sorted_emails = sorted(seen_emails)
    digest = hashlib.sha256("\n".join(sorted_emails).encode("utf-8")).hexdigest()[:12]
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    header_lines = [
        "# Edwin allowlist -- generated by backend/scripts/build-allowlist.py",
        f"# generated_at: {timestamp}",
        f"# source: {args.input.name}",
        f"# rows: {len(sorted_emails)}",
        f"# manual_extras: {len(MANUAL_EXTRAS)} declared / {len(manual_new)} new vs xlsx",
        f"# sha256_12: {digest}",
        f"# include_statuses: {args.include_statuses or '(all)'}",
        "# NOTE: This file is confidential. Do not commit. See .gitignore.",
        "",
    ]
    args.output.write_text("\n".join(header_lines) + "\n".join(sorted_emails) + "\n", encoding="utf-8")

    print("Allowlist built successfully (no PII in output).")
    print(f"  source:          {args.input}")
    print(f"  destination:     {args.output}")
    print(f"  total xlsx rows: {total_rows}")
    print(f"  emails written:  {len(sorted_emails)}")
    print(f"  sha256_12:       {digest}")
    print(f"  skipped - no email column value: {skipped_no_email}")
    print(f"  skipped - malformed email:       {skipped_bad_email}")
    print(f"  skipped - status filter:         {skipped_status}")
    print(f"  manual extras declared:          {len(MANUAL_EXTRAS)}")
    print(f"  manual extras new vs xlsx:       {len(manual_new)}")
    print()
    print("Status distribution in the source (counts only):")
    for status, count in sorted(status_counter.items(), key=lambda x: -x[1]):
        print(f"  {count:4d}  {status}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
